<?php
/**
 * @var \Gladd\DashboardShortcuts\Block\Adminhtml\Shortcuts $block
 */
?>
<div class="page-actions">
    <div class="page-actions-inner">
        <div class="page-actions-buttons">
            <?php if ($block->canShowCreateOrderButton()) : ?>
            <form class="action-element"
                  action="<?= $block->escapeUrl($block->getUrl('sales/order_create/start')) ?>"
                  method="post">
                <input
                        name="form_key"
                        type="hidden"
                        value="<?= $block->escapeHtmlAttr($block->getFormKey()) ?>"/>
                <button
                        class="action-primary"
                        type="submit"
                        title="<?= $block->escapeHtmlAttr(__('Create New Order')) ?>">
                    <?= $block->escapeHtml(__('Create New Order')) ?>
                </button>
            </form>
            <?php endif; ?>
            <?php if ($block->canShowImportButton()) : ?>
                <form class="action-element"
                      action="<?= $block->escapeUrl($block->getUrl('adminhtml/import')) ?>"
                      method="post">
                    <input
                            name="form_key"
                            type="hidden"
                            value="<?= $block->escapeHtmlAttr($block->getFormKey()) ?>"/>
                    <button
                            class="action-primary"
                            type="submit"
                            title="<?= $block->escapeHtmlAttr(__('Import')) ?>">
                        <?= $block->escapeHtml(__('Import')) ?>
                    </button>
                </form>
            <?php endif; ?>
        </div>
    </div>
</div>